language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y portaudio19-dev swig libavbin-dev libavbin0
install:
  - python setup.py install
script:
  - cd athena/tests
  - python dependencies_test.py